_wandb:
    value:
        cli_version: 0.21.0
        e:
            ree33fx063ts9xyse124z9klma9fo71x:
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "8656922775552"
                        used: "6880023339008"
                email: gptc63926@gmail.com
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-ba527751-1ef7-6d94-d1ec-b2295cc0d90e
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-9ba493c6-d94f-31be-d039-b025f0bf84dc
                host: 021205f89039
                memory:
                    total: "33662332928"
                os: Linux-6.6.56+-x86_64-with-glibc2.35
                program: kaggle.ipynb
                python: CPython 3.11.13
                root: /kaggle/working
                startedAt: "2025-08-04T13:49:28.705776Z"
                writerId: ree33fx063ts9xyse124z9klma9fo71x
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "8":
                - 1
                - 2
                - 12
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 16
epochs:
    value: 50
learning_rate:
    value: 0.001
